- .travis.yml
- requirements-test.txt
- tests/conftest.py
- tests/test_tractor.py
- tractor/__init__.py
- tractor/ipc.py
Test pretty much everything documented and that I can think of.
It's a start :)
@vodik if you want to look at this you're welcome too but it turned out to be a ton of stuff I changed to get cancellation correct - so no presh.
> Initial tests and ci

- tests/conftest.py
- tests/test_discovery.py
- tests/test_tractor.py
- tractor/_actor.py
- tractor/_ipc.py
Resolving a couple low hanging fruit issues: #7 and #16.
> Reg with uid and drop aiter_recv()

- .travis.yml
- README.rst
- tests/test_discovery.py
- tests/test_tractor.py
- tractor/__init__.py
- tractor/_actor.py
- tractor/_portal.py
- tractor/_state.py
- tractor/_trionics.py
> Add wait_for_actor() helper

- .travis.yml
> Python 3.7!

- README.rst
- tests/conftest.py
- tests/test_cancellation.py
- tests/test_spawning.py
- tests/test_streaming.py
- tractor/__init__.py
- tractor/_actor.py
- tractor/_spawn.py
- tractor/_state.py
- tractor/_trionics.py
- tractor/testing/_tractor_test.py
Resolves #60 and hopefully @chrizzFTD's #59.
> Spawn method support

- README.rst
Resolves a couple outstanding docs quiffs.
> Docs example fixes

- tractor/_ipc.py
Prepares for other possible interchange formats plus it wasn't really
a queue, just a TCP stream wrapper + `msgpack` interchange.
> Rename `StreamQueue` to `MsgpackStream`

- .travis.yml
- tests/test_discovery.py
- tests/test_multi_program.py
- tests/test_streaming.py
First attempt at resolving #62.
> Add windows CI using choco

- tractor/_forkserver_override.py
- tractor/_spawn.py
More adult, sensible name for the forkserver override code.
> Rename override module

- .travis.yml
- README.rst
- tests/test_multi_program.py
- tests/test_streaming.py
- tractor/_forkserver_override.py
- tractor/_spawn.py
This should mostly resolve #59 as well as #79 and now also #81 which gives us Python 3.8 support.
ping @chrizzFTD just to check the [new docs](https://github.com/goodboy/tractor/tree/windows_support#windows-gotchas) which detail your solution to #79.
> Windows and Python 3.8 support

- .travis.yml
Trying to fix [this weird `pip` deps resolve issue](https://travis-ci.org/goodboy/tractor/jobs/600402557). Thanks to @agronholm for [this tip](https://gitter.im/pypa/pip?at=5dacc1eb78e4974ace8fad18).
> Make pip a keener

- tests/test_cancellation.py
- tractor/_actor.py
Just spin up new events instead; because apparently they're
so cheap :roll_eyes:.
Resolves #78
> Drop use of `trio.Event.clear()`

- tests/test_cancellation.py
- tests/test_streaming.py
> Fix windows CI, again.

- setup.py
- tests/test_cancellation.py
- tests/test_streaming.py
- tractor/_actor.py
- tractor/_child.py
- tractor/_entry.py
- tractor/_spawn.py
This is duplicate of #133 but just trying to trigger CI again.
> Start up sequence trickery

- .github/workflows/ci.yml
- tests/conftest.py
- tests/test_streaming.py
I still have to do some more testing to fix some possible flakey tests, this also adds testing on mac!
> Add Github Actions CI support

- README.rst
- tractor/msg.py
See if this works:
https://github.com/goodboy/tractor/tree/matrix#feel-like-saying-hi
> Add matrix room link

- tests/test_debugger.py
- tractor/_state.py
Just fixing the stupid CI yet again.
> Fix debug tests in ci again

- tests/test_docs_examples.py
- tests/test_local.py
- tractor/_debug.py
- tractor/_root.py
- tractor/_state.py
- tractor/_trionics.py
- tractor/testing/_tractor_test.py
Another step toward #183 if we want to do it before first dev release.
I'd also be partial to getting in #182 deprecation (or just changing it outright) here.
> Implicit runtime

- docs/README.rst
- examples/parallelism/single_func.py
- setup.py
Figured, might as well and give a shout out to @richardsheridan.
First release version is added here.
Possibly `versioneer` usage and a `setup.cfg` coming in follow up PR shortly.
> Single func example

- setup.py
> First alpha

- tractor/_actor.py
- tractor/_debug.py
- tractor/_ipc.py
- tractor/log.py
apparently mucking with dark magic..
> Round 2 ci windows

- NEWS.rst
> Facepalm: fix rst hyperlinks

- NEWS.rst
- newsfragments/.gitignore
- newsfragments/HOWTO.rst
- setup.py
- towncrier.toml
To resolve #227 and get us on the road toward automated releasing (ish).
> Use `towncrier`

- .github/workflows/ci.yml
> Lengthen win CI run to 12m

- docs/README.rst
Fixes #286
I suppose there is no need for more documentation, given [this section on the README](https://github.com/goodboy/tractor/blob/master/docs/README.rst#infected-asyncio-mode)
> Remove asyncio from TODOs

- tests/test_advanced_streaming.py
- tests/test_cancellation.py
- tests/test_streaming.py
Ugh, even more tolerant timeouts for windows and py 3.10 to make CI happy.
> Moar timeoutz

- .github/workflows/ci.yml
- MANIFEST.in
This should hopefully catch issues like,
https://github.com/goodboy/tractor/issues/293
> Add an sdist install job

- .github/workflows/ci.yml
- nooz/316.misc.rst
- setup.py
> Try windows CI on py 3.10

- .github/workflows/ci.yml
- docs/README.rst
- nooz/317.misc.rst
- setup.py
- tractor/_ipc.py
Go full in on `msgspec` as we plan for a `3.10`+ version in our alpha 6.
Resolves #313.
> Drop `msgpack`
