goodboy/tractor

- .travis.yml
- tests/test_tractor.py
- tractor/__init__.py
- tractor/_actor.py
- tractor/_portal.py
- tractor/_trionics.py
Stop worrying about a "main task" in each actor and instead add an
additional `ActorNursery.run_in_actor()` method which wraps calls
to create an actor and run a lone RPC task inside it. Note this
adjusts the public API of `ActorNursery.start_actor()` to drop
its `main` kwarg.
The dirty deats of making this possible:
- each spawned RPC task is now tracked with a specific cancel scope such
that when the actor is cancelled all ongoing responders are cancelled
before any IPC/channel machinery is closed (turns out that spawning
new actors from `outlive_main=True` actors was probably borked before
finally getting this working).
- make each initial RPC response be a packet which describes the
`functype` (eg. `{'functype': 'asyncfunction'}`) allowing for async
calls/submissions by client actors …
> Drop the "main" task via kwarg idea

- tractor/_actor.py
- tractor/_forkserver_hackzorz.py
- tractor/_ipc.py
- tractor/_portal.py
- tractor/_trionics.py
Temporary solution for #6 by overriding some stdlib code in `multiprocessing.forkserver.py`.
A proper patch should be made eventually to get this more granular server management into the stdlib. For more detailed discussion see #20.
@vodik ping ping!
> Forkserver singleton

- README.md
- README.rst
- setup.py
- tests/test_tractor.py
There is a slew of tests to match and verify everything documented thus far. 
Hopefully it's a decent little start :)
pinging @vodik, @dnephin, @nonsleepr and @Konstantine00 since you all expressed interest (or gave me permission to bug you) to take a look at this.
Please feel free to be honest and grill what you don't like :+1: 
Rendered version is [here](https://github.com/tgoodlet/tractor/tree/draft_readme).
Thanks!
> Initial readme documenting most features

- tests/test_tractor.py
- tractor/_forkserver_hackzorz.py
Tweak the cancel tests to use a delay based on a single successful run; the cancel delay should be less then the time it takes a run to complete. This should avoid flaky tests across python versions and environments.
Also included is a fix for py3.7 which ensures our overridden `forkserver.py` stuff is properly imported when the server is first spun up.
> Reliable cancel tests

- .travis.yml
- requirements-test.txt
- tractor/__init__.py
- tractor/_actor.py
- tractor/_forkserver_hackzorz.py
- tractor/_ipc.py
- tractor/_portal.py
- tractor/_state.py
- tractor/_trionics.py
- tractor/log.py
This is purely for documentation purposes for now as it should be
obvious a bunch of the signatures aren't using the correct "generics"
syntax (i.e. the use of `(str, int)` instead of `typing.Tuple[str, int])`)
in a bunch of places. We're also not using a type checker yet and besides,
`trio` doesn't really expose a lot of its internal types very well.
cc @vodik
> Add type annotations to most functions

- tests/test_cancellation.py
- tests/test_multi_program.py
- tests/test_streaming.py
- tractor/__init__.py
- tractor/_actor.py
- tractor/_exceptions.py
- tractor/_portal.py
- tractor/_trionics.py
This overhauls the cancellation / error propagation machinery:
- Unwrap remote error types and try to map them to a local type (still haven't quite figured out an API for catching such boxed error types but it might eventually look something like [MultiError.catch()](https://trio.readthedocs.io/en/latest/reference-core.html#trio.MultiError.catch))
- full `ActorNursery` support for [`trio.MultiError`](https://trio.readthedocs.io/en/latest/reference-core.html#trio.MultiError) and multi-actor errors with the [same semantics as `trio`](https://trio.readthedocs.io/en/latest/reference-core.html#errors-in-multiple-child-tasks)
- clearer distinction between internal `tractor._exceptions.InternalActorError` and remote errors, the former being raised when there's bugs in `tractor` internals
@vodik …
> Improved errors - introduce trio.MultiError

- setup.py
- tests/conftest.py
- tests/test_multi_program.py
- tractor/_tractor_test.py
- tractor/testing/__init__.py
- tractor/testing/_tractor_test.py
Copy the way `trio` does it. Adjust tests to match.
> Expose `tractor_test` for external use

- tractor/_actor.py
I'm not sure how this ever worked but when a "fake" async gen
(i.e. function with special `chan`, `cid` kwargs) is completed
we need to signal the end of the stream just like with normal
async gens. Also don't fail when trying to remove tasks that were
never tracked.
Fixes #46
> Stop channel based async gen streams on exit

- tractor/testing/_tractor_test.py
For `pytest`, support defining a `loglevel` fixture value which will be
passed into internals when using `@tractor_test`.
> Support `loglevel` fixture injection

- tests/test_rpc.py
- tractor/__init__.py
- tractor/_actor.py
- tractor/_exceptions.py
Don't crash remote actors on remote module/function lookup errors.
Instead ship the error back to the caller.
> Remote module errors

- .travis.yml
- README.rst
- setup.py
- tests/test_local.py
- tests/test_pubsub.py
- tests/test_rpc.py
- tractor/__init__.py
- tractor/_actor.py
- tractor/_exceptions.py
- tractor/_ipc.py
- tractor/_portal.py
- tractor/_trionics.py
- tractor/msg.py
An attempt at providing a very basic implementation of a *context* similar to [that offered in `nanomsg`](https://nanomsg.github.io/nng/man/v1.1.0/nng_ctx.5).
Also adding a `@tractor.msg.pub` publisher async gen decorator system.
This allows for building inter-actor on-demand streaming APIs.
Some other bug fixes regarding remote import-time error handling is also included.
ping @vodik @Konstantine00
> Contexts and Pub-Sub

- README.rst
- setup.py
- tests/test_multi_program.py
- tests/test_pubsub.py
- tests/test_streaming.py
- tractor/_actor.py
- tractor/_portal.py
- tractor/_state.py
- tractor/_trionics.py
- tractor/msg.py
`trio` deprecated the old `Queue` in `0.11.0` and introduced the new [`trio.open_memory_channel()`](https://trio.readthedocs.io/en/latest/reference-core.html#using-channels-to-pass-values-between-tasks) system. Adopt this throughout the core and adjust all tests.
In other fun news, we were also suffering from a super subtle bug in Python itself, namely:
https://bugs.python.org/issue32526
This was the root cause of a slew of issues in some UI work in `piker`.
It turns out (at least with `trio`) asyn gen functions are **not** task safe and can cause all sorts of strange issues if operated on by multiple tasks. Thanks to [in depth diagnosis on the gitter channel](https://gitter.im/python-trio/general?at=5c65bb42dc3f0523ccb6a1ac), the alternative is to introduce an async iterator derivative …
> Use trio memory channels!

- README.rst
- tests/test_streaming.py
Resolves #65
@parity3 mind giving that a once over to be sure it solves your critique.
New streaming example is [here](https://github.com/tgoodlet/tractor/tree/close_mem_chans#a-full-fledged-streaming-service).
> Use "clean channel shutdown" in streaming example

- tests/conftest.py
- tests/test_discovery.py
- tests/test_multi_program.py
- tractor/_spawn.py
This PR is to get the testsuite passing on windows.
Current failures occur on `test_streaming`. I've noticed that the process finishes in less time than `delay` [here](https://github.com/tgoodlet/tractor/blob/c0276c85dfa4688d76ca649e7edb8db89170dcbe/tests/test_streaming.py#L191 ) and [here](https://github.com/tgoodlet/tractor/blob/c0276c85dfa4688d76ca649e7edb8db89170dcbe/tests/test_streaming.py#L169), sometimes it's like half a second faster.
Since it looks like hardware related, probably that could be addressed on a different PR?
<details>
<summary>Full log of tests here:</summary>
```log
(tractor_test19031001) B:\write\code\git\tractor>python -m pytest "tests/"
===================================================================================== test session starts …
```
> Update tests for windows

- tests/test_spawning.py
- tractor/__init__.py
- tractor/_trionics.py
> Propagate `tractor.run()` logging level to subactors

- README.rst
- tests/test_streaming.py
- tractor/__init__.py
- tractor/_actor.py
- tractor/_discovery.py
- tractor/_ipc.py
- tractor/_portal.py
- tractor/_streaming.py
- tractor/msg.py
Require explicitly decorated stream functions using `@tractor.stream` such that we can raise a `TypeError` on a missing `ctx` arg.
Still needs tests.
Reorged the streaming section in the docs.
> Stream functions

- README.rst
- setup.py
- tests/conftest.py
- tests/test_cancellation.py
- tests/test_discovery.py
- tractor/_actor.py
- tractor/_exceptions.py
- tractor/_trionics.py
Attention all lurkers: code reviews and specifically criticisms are appreciated!
This is mostly to resolve #43 but I created some related issues (#87, #88, #89) after thinking and working through other types of failure cases we need to handle.
The main solution to get this working was adding proper `MultiError` propagation support in the core.
Interestingly writing the nested sub-actor error propagation tests actually found some serious holdups in the `multiprocessing` forkserver code. Even with my patches to the stdlib (which are pretty questionable) the server breaks pretty easily (causing hangs) when spawning any more then a couple "levels" (really lifetime scopes) of process tree. It's all good fodder for #84 and either writing our own forkserver or looking at the proper way to get …
> More thorough basic supervision tests

- .travis.yml
- requirements-test.txt
- setup.py
- tractor/__init__.py
- tractor/_actor.py
- tractor/_ipc.py
- tractor/_portal.py
- tractor/_spawn.py
- tractor/_state.py
- tractor/_trionics.py
- tractor/log.py
Prepend the actor and task names in each log emission. This makes
debugging much more sane since you can see from which process and
running task the log message originates from!
Resolves #13
> Log task and actor names where possible

- README.rst
This was originally bundled in #102 but the windows CI there has blocked
that from landing quickly. These examples need to be fixed stat since
I've had at least a couple people notice it now when first trying out
the project.
Ping @salotz and @dxflores.
> Add script "guards" to docs examples

- README.rst
- examples/__main__.py
- examples/a_trynamic_first_scene.py
- examples/actor_spawning_and_causality.py
- examples/asynchronous_generators.py
- examples/full_fledged_streaming_service.py
- examples/service_discovery.py
- tests/test_docs_examples.py
- tractor/_actor.py
- tractor/_discovery.py
- tractor/_portal.py
- tractor/_spawn.py
A per #98 we need tests for examples from the docs as they would be run
by a user copy and pasting the code. This adds a small system for loading
examples from an "examples/" directory and executing them in
a subprocess while checking the output.
I am open to other suggestions but I think this approach will work well along with plans to literal include examples in sphinx docs as mentioned in #99.
@salotz @ryanhiebert give this a peak if you don't mind :)
> Test docs examples as scripts

- setup.py
- tests/test_cancellation.py
- tests/test_streaming.py
- tractor/_actor.py
- tractor/_child.py
- tractor/_entry.py
- tractor/_spawn.py
In the new trio backend, we were using cloudpickle to serialize the async function the child will have to pass to trio to run, but this function never changed, it was `Actor._async_main`, this function handles the connection and handshake with the parent actor.
The real problem was passing the subactor object instance to the newly spawned child.
`tractor._actor.Actor` init function params:
- name: `str`,
- rpc_module_paths: `List[str]`,
- uid: `str`,
- loglevel: `str`,
- arbiter_addr: `Tuple[str, int]`
This parameters are passed through the child shell arguments and parsed using `argparse`.
The problem is the following, when running `tests/_test.py` from the shell this is the output:
```
[guille@hardPC tractor]$ python tests/_test.py 
Jul 25 16:42:27 (no actor context, 161699, …
```
> Drop cloudpickle dependency

- tests/conftest.py
- tests/test_discovery.py
- tests/test_multi_program.py
- tractor/_actor.py
- tractor/_discovery.py
- tractor/_entry.py
- tractor/_ipc.py
- tractor/_spawn.py
- tractor/_trionics.py
This is a (finally) reproduction of the issue I discovered manually in #141; it was likely a regression (caused by #128) but it's hard to know since we didn't have tests for this until now :smile:
It turns out the issue only appears if you are in the middle of consuming and infinite stream and are cancelled.
The cancellation causes the `trio.Process` backend to kill the process before it can cleanup resulting in stale entries in the arbiter registry.
This first set of commits will demonstrate the issue (that I want to see also in CI) and then I will push up the solution commit :surfer:
> Ensure actors de-register with arbiter when cancelled during infitinite streaming.

- setup.py
- tests/conftest.py
- tests/test_discovery.py
- tests/test_local.py
- tests/test_pubsub.py
- tractor/__init__.py
- tractor/_actor.py
- tractor/_portal.py
- tractor/_spawn.py
- tractor/_trionics.py
- tractor/msg.py
- tractor/testing/_tractor_test.py
There was code from the last de-registration fix PR (#141, #143) that [I had commented](https://github.com/goodboy/tractor/blob/master/tractor/_actor.py#L681)
(to do with shielding arbiter dereg steps in `Actor._async_main()`) because
the block didn't seem to make a difference under infinite streaming
tests. 
Turns out it for sure is needed if you manually close the stream **before** cancelling the containing nursery.
Pushing up a test to demonstrate the failure then will push up a fix to correct.
**UPDATE**: this ended up being a much bigger change set see comment below.
- Long story short, getting things to work reliably led to some reworking of cancellation machinery in terms of internal nursery composition. 
- I tried bringing code from newer feature branches to solve this …
> Fix for dereg failure on manual stream close

- .travis.yml
Small gaf on my part, in #137 I put the docs requirements in a separate file and forgot to update the `.travis.yml` file to also install that file when running tests.
> Install docs requirements in travis tests

- examples/debugging/multi_daemon_subactors.py
- tests/test_debugger.py
- tractor/__init__.py
- tractor/_actor.py
- tractor/_discovery.py
In piker we rely on hooking into `tractor._main()` so set the `_is_root` runtime var in there instead.
Toss in another debugger test for good measure :surfer:
> Debug refine

- tractor/log.py
For projects that use the internal pretty logging system (such as `piker`) it's annoying to see the project-package name duplicated in log msg headers when using `tractor.log.get_logger(__name__)` from inside the client module:
prefer `piker.mod.submod submod.py:439` vs `piker.piker.mod.submod submod.py:439`
This just strips that duplicate token if detected while still keep the child logging hierarchy in tact.
> Drop duplicate project-package name in msg header

- examples/debugging/root_cancelled_but_child_is_in_tty_lock.py
- tests/test_debugger.py
- tractor/__init__.py
- tractor/_actor.py
- tractor/_debug.py
- tractor/_entry.py
Turns out this is a lower level issue in terms of the stdlib's default
`pdb.Pdb` settings and how they conflict with `trio`s cancellation and
KBI handling. The details are hashed out more thoroughly in
python-trio/trio#1155. Maybe we can get a fix in trio so things are
solved under our feet :)
> End the `pdb` SIGINT handling madness

- tests/test_debugger.py
- tests/test_streaming.py
- tractor/_ipc.py
- tractor/_portal.py
Add a ``tractor._portal.StreamReceiveChannel.shield_channel()`` context manager which allows for avoiding the closing of an IPC stream's underlying channel for the purposes of task re-spawning. 
Sometimes you might want to cancel a task consuming a stream but not tear down the IPC
between actors (the default). A common use can might be where the task's "setup" work might need to be redone but you want to keep the established portal / channel in tact despite the task restart.
Includes a test.
I'm still not sure on the name here..
Any opinions @salotz , @guilledk?
Note it's used inside a `with stream.<meth name>`
Short list:
- `.shield_channel()`
- `.shielded_channel()`
- `.shield()`
- just make a `bool` property `.shield` you assign manually?
- `.shield_from_close()`
- …
> Add a way to shield a stream's underlying channel

- docs/index.rst
- examples/a_trynamic_first_scene.py
- examples/actor_spawning_and_causality.py
- examples/actor_spawning_and_causality_with_daemon.py
- examples/asynchronous_generators.py
- examples/debugging/multi_daemon_subactors.py
- examples/debugging/multi_nested_subactors_error_up_through_nurseries.py
- examples/debugging/multi_subactor_root_errors.py
- examples/debugging/multi_subactors.py
- examples/debugging/root_cancelled_but_child_is_in_tty_lock.py
- examples/debugging/subactor_breakpoint.py
- examples/debugging/subactor_error.py
- examples/full_fledged_streaming_service.py
- examples/remote_error_propagation.py
- tests/test_cancellation.py
- tests/test_debugger.py
- tests/test_discovery.py
- tests/test_local.py
- tests/test_pubsub.py
- tests/test_rpc.py
- tests/test_spawning.py
- tests/test_streaming.py
- tractor/__init__.py
- tractor/_actor.py
- tractor/_debug.py
- tractor/_discovery.py
- tractor/_portal.py
- tractor/_spawn.py
- tractor/_trionics.py
- tractor/msg.py
This resolves and completes #69 allowing all RPC invocation APIs to pass
function references directly instead of explicit `str` names for the
target namespace and function (this is still done implicitly
underneath).  This brings us closer to `trio`'s task running API as well
as acknowledges that any inter-host RPC system (and API) will likely
need to be implemented on top of local RPC primitives anyway. Even if
this ends up **not** being true we can always go to "function stubs" as
part of our IAC protocol or, add a new method to do explicit namespace
calls: `.run_from_module()` or whatever everyone votes on.
Resolves #69
Further, this commit drops `Actor.statespace` from the entire system
since a user can easily get this same functionality using module
level variables. Fix docs to match …
> Allow passing function refs to `Portal.run()`

- examples/debugging/multi_subactor_root_errors.py
- tests/test_debugger.py
- tractor/_actor.py
- tractor/_debug.py
- tractor/_exceptions.py
- tractor/_ipc.py
- tractor/_trionics.py
- tractor/log.py
Some minimal effort to reduce `error` logging to warnings.
Change default logging level to `error` to aid with this.
> Denoise logging

- tractor/_actor.py
- tractor/_portal.py
- tractor/_root.py
- tractor/_spawn.py
- tractor/_streaming.py
- tractor/_trionics.py
- tractor/msg.py
Start at #182.
Adds warning for now to allow transitioning client code in the short term.
> Begin rpc_module_paths deprecation

- examples/multiple_streams_one_portal.py
- tractor/_actor.py
- tractor/_portal.py
- tractor/_root.py
- tractor/_spawn.py
- tractor/_streaming.py
- tractor/_trionics.py
- tractor/msg.py
@guilledk that thing i was talkin bout..
This definitely pertains to #145 but does not yet solve it.
> We aint got zombie shields

- tractor/_debug.py
- tractor/_entry.py
- tractor/_mp_fixup_main.py
- tractor/_root.py
Override `breakpoint()` for sync code making it work
properly with `trio` as per:
https://github.com/python-trio/trio/issues/1155#issuecomment-742964018
Relates to #193
Pretty sure this also gets us working `asyncio` actor debugging (from manual anectdote) but needs further testing on that branch.
> Support sync code breakpointing via built-in

- examples/actor_spawning_and_causality.py
- examples/actor_spawning_and_causality_with_daemon.py
- examples/parallelism/concurrent_actors_primes.py
- setup.py
- tests/test_cancellation.py
- tests/test_spawning.py
- tractor/_actor.py
- tractor/_portal.py
Resolves #77.
Realized we had a bunch of arbiter methods that were sync and of course now the concurrent primes example function needs to be async. Looks a little unwelcoming imo but then again if peeps are here and don't want to make everything `async` maybe it's the wrong spot 😂 
Also, as mentioned in the readme, [`trio-parallel`](https://github.com/richardsheridan/trio-parallel) for anyone who wants the sync func support.
> Drop sync func invocation support.

- examples/asynchronous_generators.py
- examples/debugging/multi_daemon_subactors.py
- examples/debugging/subactor_breakpoint.py
- examples/full_fledged_streaming_service.py
- examples/multiple_streams_one_portal.py
- tests/test_cancellation.py
- tests/test_discovery.py
- tests/test_pubsub.py
- tests/test_streaming.py
- tractor/_actor.py
- tractor/_debug.py
- tractor/_exceptions.py
- tractor/_ipc.py
- tractor/_portal.py
- tractor/_spawn.py
- tractor/_state.py
- tractor/_streaming.py
- tractor/_trionics.py
- tractor/msg.py
This is a breaking change to remove support for [streaming using `Portal.run()`](https://tractor.readthedocs.io/en/latest/#asynchronous-generators) calls and instead replace it with a new `@asynccontextmanager` api `Portal.open_stream_from() as stream:`.
The main motivation for this is that it avoids leaving users to do there own manual stream shutdown management (normally ala `async_generator.aslosing()` or the new `aclosing()` coming in the stdlib) and promotes more stringent SC style in streaming clients. That latter part is important as we move shortly to supporting an api for #53 which will require explicit *cross-actor-context* management.
The basic gist should be clear from the changed tests.
Once this is merged **it will break old code**.
> Stream contexts

- tractor/_root.py
- tractor/_spawn.py
Might solve some of the complaints in any of:
#84 #89 #134 #146
Still want to test enabling the nested spawning tests again to see if we get any improvements.
> Mp teardown hardening

- docs/README.rst
- docs/conf.py
- docs/index.rst
- requirements-docs.txt
README bump for #210 as well a new docs theme which still has some stuff to work through (re: https://github.com/goodboy/tractor/issues/157#issuecomment-788931935).
I'd like to get our docs looking super polished before next release with a proper tutorial set as per #157.
Please feel free to (in particular) criticize the heck out of the readme update.
> New docs polish

- setup.py
- tests/test_cancellation.py
- tests/test_debugger.py
- tractor/_actor.py
- tractor/_exceptions.py
- tractor/_ipc.py
- tractor/_root.py
Pulls out some transport related finessing into a new small patchset for other PRs (like #209) to build on.
Mostly trying to get these lower level changes in and see it work in CI.
> Transport cleaning

- .github/workflows/ci.yml
- docs/README.rst
- examples/rpc_bidir_streaming.py
- tests/test_2way.py
- tests/test_advanced_streaming.py
- tests/test_debugger.py
- tests/test_docs_examples.py
- tests/test_streaming.py
- tractor/__init__.py
- tractor/_actor.py
- tractor/_debug.py
- tractor/_discovery.py
- tractor/_exceptions.py
- tractor/_ipc.py
- tractor/_portal.py
- tractor/_root.py
- tractor/_spawn.py
- tractor/_streaming.py
- tractor/_trionics.py
- tractor/log.py
- tractor/msg.py
- tractor/testing/_tractor_test.py
This is a first draft of a *bidirectional streaming* api as discussed in #53.
This specific PR is a clone of the original #209 but with debugger changes factored out to see if we can get a clean CI run as well as a smaller patch set for reviewers. There is a follow up PR #220 which includes the debugger improvements that now use and rely on this new api.
Critique and suggestions very welcome from lurkers 😎.
---
- ~[ ] should we add broadcasting support here for #204 ?~ let's keep it separate.
/api.html#anyio.streams.stapled.StapledObjectStream) (obvs we won't use `*Object*` since we're `msgpack` type contrained). Actual code is [here](https://github.com/agronholm/anyio/blob/master/src/anyio/streams/stapled.py#L46).
- docs on the new apis
- possibly a better internal design for tracking …
> Bi streaming no debugger stuff

- examples/debugging/fast_error_in_root_after_spawn.py
- examples/debugging/root_timeout_while_child_crashed.py
- tests/test_debugger.py
- tractor/_actor.py
- tractor/_debug.py
- tractor/_exceptions.py
- tractor/_root.py
- tractor/_spawn.py
- tractor/_trionics.py
Clone of #217 but with commits factored to pair with #219.
Again trying to find the source commits that breaks windows CI...
In theory this should have the same CI results as #217 but who knows any more 😂
> Ctx debugger

- NEWS.rst
News fragments for an `.alpha1` release that I'd like to get out tomorrow 😎 
ping @Fuyukai.
For the *trio feed* what markup would you prefer for the summary of this?
In markdown it'll likely go something like:
---
For those who haven't heard of us, ``tractor`` is a multi-processing-runtime library which applies structured concurrency from the ground up on process managment and IPC. We had our first alpha release this past Feb. and now our second this Aug. 1st 🥳.
The quick and dirty summary for this release is:
- Updated our unidirectional streaming APIs to be more `async_generator.aclosing()`-like
- Vastly improved our actor reaping during cancellation and error propagation for the `multiprocessing` spawner backend
- Added a next-gen, fully bi-directional streaming API with complete, …
> Add .alpha1 news flash

- examples/asynchronous_generators.py
- tests/test_debugger.py
- tractor/_root.py
- tractor/_trionics.py
Trying to get debugger tests more deterministic.
- Better early timeout handling
- send `continue`s on child re-locks of tty
More coming.
> Debugger tests determinism

- newsfragments/230.removal.rst
- tests/test_streaming.py
- tractor/_streaming.py
Before we had `async with Portal.open_stream_from()` which has explicit enter/exit semantics, we had a implicit *portal-returns-stream-reference* thing which required that if a `stream.receive()` was cancelled, we relayed that via a stream closure to the other side.
Since we have the new API now we don't need this shielding (aka we won't `.aclose()` the stream on cancellation) any more.
This PR removes all that and the CI should prove that all things are well. 
Once CI is clean I'll just remove the first patch draft which comments all the unneeded code.
> Drop stream shielding; it was from a legacy api design

- newsfragments/234.bugfix
- tractor/__init__.py
- tractor/_debug.py
- tractor/_entry.py
- tractor/_trionics.py
Debugger improvements to avoid even further tty clobbering edge cases and potential root actor hangs when the debug lock is acquired but the child completes or intends to release it but the root never is notified.
> Root tty hangs

- newsfragments/166.feature.rst
- setup.py
- tractor/_spawn.py
Was able to try it manually on a windows 10 system and the debugger
works great!
> Flip to using the `trio` spawner on windows

- newsfragments/239.bug.rst
- tests/test_2way.py
- tests/test_advanced_streaming.py
- tests/test_task_broadcasting.py
- tractor/_portal.py
- tractor/_streaming.py
- tractor/log.py
Fix for an issue discovered in the development of [`wrath`](https://github.com/adder46/wrath) - thanks to @adder46!
It turns out we need to catch KBI's in `Portal.open_context()` blocks in order to get proper cancellation *if* the block is run inside the top level task (maybe always).  The fix for this is simple, we just need to either explicitly handle the kbi in the block's `__aenter__()` implementation or just handle `BaseException` (which is the likely solution).
Tests are up first to show CI failures, patch will come shortly after.
> Fix kbi in ctx block

- docs/README.rst
- docs/dev_tips.rst
- examples/quick_cluster.py
- tractor/_clustering.py
Adds an example and mirrors it in the readme.
I tweaked the auto-generated names for actors created with `open_actor_cluster()` to be simpler (since they had this weird `.uid` string thing going on) to be simply `<parent_name>.<name>`.
Oh right, and started a little internal *dev tips* doc just for reminding myself of stuff.
It needs lots more content don't worry.
> Clusters and hot tips

- tractor/_actor.py
- tractor/_debug.py
A bug fix for debug lock acquirer helper and a fix for the early actor termination case where the TCP server never fully comes up before the runtime is killed.
> Early deth fixes

- newsfragments/264.bug.rst
- tests/test_spawning.py
- tractor/_portal.py
`None` was being used as the *cached result* flag and obviously breaks on a `None` returned from the remote target task 😂 . This would cause an infinite hang if user code ever called `Portal.result()` *before* the nursery exit..
Simple fix by just using the `Channel.uid` as the initial *no result yet received yet* flag.
> Fix `Portal.run_in_actor()` returns `None` result

- newsfragments/266.bug.rst
- tests/test_cancellation.py
- tractor/_spawn.py
This was *kind of* a bug where if the soft wait (`await .proc.wait()`) in the reaper task was cancelled we could fail over to the *hard reap sequence* which has a timeout of 3s (currently) before system signalling the subproc.
This adds a test to catch that *slower then necessary* reaping delay and adds the fix where if the graceful daemon actor proc wait is cancelled we relay that cancellation to the actor via `Portal.cancel_actor()` which should result in a much faster graceful teardown.
I'm pretty sure I already worked through some of this in the (now history mangled)  [zombie lord](https://github.com/goodboy/tractor/commits/zombie_lord_infinite) branch..
> Faster graceful daemon cancels

- newsfragments/267.misc.rst
- tests/test_cancellation.py
- tractor/_actor.py
- tractor/_ipc.py
- tractor/_portal.py
- tractor/_spawn.py
- tractor/_supervise.py
This finally adds fully acknowledged remote cancellation messaging support for both explicit `Portal.cancel_actor()` calls as well as the same for runtime-wide cancellations (eg. during kbi or general actor nursery exception handling).
You can think of this as the *most ideal case* in [2-generals](https://en.wikipedia.org/wiki/Two_Generals%27_Problem#Engineering_approaches) where the actor requesting the cancel of its child is able to always receive back the ACK to that request. This leads to a more deterministic teardown where the parent is able to wait for the child to fully respond to the request. On a localhost setup (where the parent can monitor the state of the child through process or other OS apis instead of solely through messaging) the first parent can know whether or not the …
> Acked remote cancels

- examples/debugging/per_actor_debug.py
- newsfragments/271.feature.rst
- tests/conftest.py
- tests/test_debugger.py
- tractor/_debug.py
- tractor/_root.py
- tractor/_spawn.py
- tractor/_supervise.py
- tractor/log.py
Draft try at allowing per-actor debug mode control(s). 
Also some fixes to the test suite to actually use correct log level settings as well as some logic to use `PDB` level logging by default whenever `debug_mode=True` is set.
This this probably could use some tests?
> Debug flag per actor

- LICENSE
- tractor/__init__.py
- tractor/_actor.py
- tractor/_child.py
- tractor/_clustering.py
- tractor/_debug.py
- tractor/_discovery.py
- tractor/_entry.py
- tractor/_exceptions.py
- tractor/_forkserver_override.py
- tractor/_ipc.py
- tractor/_mp_fixup_main.py
- tractor/_portal.py
- tractor/_root.py
- tractor/_spawn.py
- tractor/_state.py
- tractor/_streaming.py
- tractor/_supervise.py
- tractor/log.py
- tractor/msg.py
- tractor/testing/__init__.py
- tractor/testing/_tractor_test.py
- tractor/trionics/__init__.py
- tractor/trionics/_broadcast.py
- tractor/trionics/_mngrs.py
This commit obviously denotes a re-license of all applicable parts of
the code base (not including the minor patch setl not yet verified by
contributors). From here henceforth all changes will be AGPLv4 licensed
and distributed. This is purely an effort to maintain the same copy-left
policy whilst closing the SaaS loophole the GPLv4 allows for. It is
merely for this loophole, to avoid code hiding by any potential firms
who are attempting to use the project to make a profit without either
compensating the authors or re-distributing their changes.
I thought quite a bit about this change and can't see a reason not to
close the SaaS loophole in our current license. We still are (hard)
copy-left and I plan to keep the code base this way for a couple
reasons:
- The code base produces …
> Re-license code base for distribution under AGPLv4

- LICENSE
- tractor/__init__.py
- tractor/_actor.py
- tractor/_child.py
- tractor/_clustering.py
- tractor/_debug.py
- tractor/_discovery.py
- tractor/_entry.py
- tractor/_exceptions.py
- tractor/_forkserver_override.py
- tractor/_ipc.py
- tractor/_mp_fixup_main.py
- tractor/_portal.py
- tractor/_root.py
- tractor/_spawn.py
- tractor/_state.py
- tractor/_streaming.py
- tractor/_supervise.py
- tractor/log.py
- tractor/msg.py
- tractor/testing/__init__.py
- tractor/testing/_tractor_test.py
- tractor/trionics/__init__.py
- tractor/trionics/_broadcast.py
- tractor/trionics/_mngrs.py
Redo of #274 but just fixing the commit message 😂 (which had a wrong license version number)..
I'm pedantic and would rather not have a non-existent  license version in the history, lul.
Already force pushed master to remove that commit (sorry lurkerz if you pulled).
Just putting this up to get the merge commit; sign offs from contribs were already acked in #274 despite the wrong AGPL version mentioned in the GH issue commit message. The patch set was all correct.
> Re-license as AGPLv3*

- newsfragments/278.bug.rst
- requirements-test.txt
- tests/test_advanced_streaming.py
- tests/test_streaming.py
- tractor/_streaming.py
- tractor/trionics/_broadcast.py
This patch set is factored out of #257 and corrects a bunch of previously unknown bugs to do with stream closure and broadcast receiver usage around streams as provided by `MsgStream.subscribe()`.
I decided to pull the work out of the other PR because this is notably different work despite discovering it via the original cached-inter-actor stream test that found it.
Summary:
- add a `MsgStream._closed: bool` for internal closure tracking and raise `trio.ClosedResourceError` in `.send()` if set 
- always set `MsgStream._eoc: bool` inside `.aclose()`
- always set `._eoc` when a `'stop'` message is received
- add `.eoc: bool` and `.cancelled: bool` tracking inside `BroadcastState`, set these flags on handling of the appropriate `trio` exceptions as well as wake all broadcast consumers on …
> End of channel fixes for streams and broadcasting

- newsfragments/257.feature.rst
- tests/test_resource_cache.py
- tractor/_root.py
- tractor/trionics/__init__.py
- tractor/trionics/_broadcast.py
- tractor/trionics/_mngrs.py
Like it sounds: a context manager that only opens a new actor-global (aka mem local) resource if one isn't already cached.
This is particularly handy for resources that can be shared by multiple tasks in and actor where the user desires that the lifetime of the resource is maintained until the final *user task* completes.
Still needs tests obviously.
UPDATE:
This ended up turning into a foray into fixing `MsgStream` closure/termination semantics after trying to get the original resource caching test working.
Todo tests:
> Add `maybe_open_context()` an actor wide task-resource cache

- requirements-test.txt
- tests/test_context_stream_semantics.py
- tractor/_actor.py
- tractor/_portal.py
- tractor/_streaming.py
Fix for https://github.com/pikers/piker/issues/244 which addresses an issue where if a `Context` is cancelled due to one side erroring, we **don't want to** mask that orignal source error with the `ContextCancelled` which is responded back from the callee side which was cancelled as part of the caller side's error handling.
So in other words,
- caller opens a context with callee
- caller errors inside its context and the error handling sends a `Context.cancel()` request to the callee
- the callee side handles that cancel request and sends back a `ContextCancelled`
- the caller receives the `ContextCancelled` but should not override the local `Context._error` value with the cancel request response
- the caller should raise the original source error
> Expected ctx cancelled should not override a source error

- .github/workflows/ci.yml
- docs/README.rst
- examples/infected_asyncio_echo_server.py
- newsfragments/121.feature.rst
- tests/test_cancellation.py
- tests/test_docs_examples.py
- tests/test_infected_asyncio.py
- tractor/_actor.py
- tractor/_child.py
- tractor/_entry.py
- tractor/_exceptions.py
- tractor/_root.py
- tractor/_spawn.py
- tractor/_supervise.py
- tractor/to_asyncio.py
- tractor/trionics/_broadcast.py
[README blurb](https://github.com/goodboy/tractor/tree/infect_asyncio#infected-asyncio-mode) summarizing this new feature.
What I hope to be a successful attempt at solving #120.
This gets us the following very interesting functionality:
- ability to spawn an actor that has a process entry point of `asyncio.run()`
- the `asyncio` actor embeds `trio` using the [new guest mode](https://github.com/python-trio/trio/blob/master/notes-to-self/aio-guest-test.py) which then enters the `tractor.Actor._async_main()` entry point thus engaging all the std IPC machinery
- the actor is now able to accept requests for async functions which can utilize the new `tractor.to_asyncio.run()` method which allows spawning tasks in the host `asyncio` loop and waiting/streaming the result(s) back into the `trio` …
> Infect `asyncio`

- nooz/248.misc.rst
- setup.py
- tractor/_spawn.py
- tractor/trionics/_mngrs.py
Adjust the `soft_wait()` strategy to avoid sending needless cancel
requests if suitable.
Basically an even more graceful handling of actor cancellation for parent-child peers.
> Cancel the `.cancel_actor()` request on proc death

- nooz/295.misc.rst
- tractor/_portal.py
- tractor/msg.py
Discussion in #294 and looking for scrutiny and feedback on how this might play well with our `ActorNursery.start_actor(<name>, enable_modules:list[str])` module capability system.
> `NamespacePath`: a message compatible "object reference" type

- nooz/300.misc.rst
- setup.py
- tests/test_discovery.py
- tractor/_actor.py
- tractor/_ipc.py
- tractor/trionics/_mngrs.py
As per https://github.com/jcrist/msgspec/issues/30#issuecomment-869084723 there's not much of a benefit in our use case (IPC messaging often with dynamic lists) and we can always (and are planning to) support native structs eventually anyway.
The further benefit is that we can assume `msgspec` and `msgpack` will be uniform in the array format after decode. 
Relates to https://github.com/goodboy/tractor/issues/196 and https://github.com/goodboy/tractor/issues/294.
> Use lists by default like `msgspec`, update to latest `msgspec`  and `msgpack` releases

- tests/test_infected_asyncio.py
Post-op from https://github.com/goodboy/tractor/pull/304 just to get the test more reliable since windows has order issues apparently likely due to slight scheduling/latency differences..
> Sort `.subscribe()` results before comparison in test

- 305.misc.rst
- tractor/__init__.py
- tractor/_discovery.py
Sometimes it's handy to just have a non-`Portal` yielding way
to figure out if a "service" actor is up, so add this discovery
helper for that. We'll prolly just leave it undocumented for
now until we figure out a longer-term/better discovery system.
> Add `tractor.query_actor()` an addr looker-upper

- examples/infected_asyncio_echo_server.py
- nooz/318.bug.rst
- tests/test_infected_asyncio.py
- tractor/to_asyncio.py
Turns out the `to_asyncio.` stuff wasn't robust enough to handle this;  we weren't propagating errors from an IPC context embedded task opened via `.open_channel_from()`..
---
To start this adds 2 more tests:
> Add context test that opens an inter-task-channel that errors

- .github/workflows/ci.yml
- examples/debugging/open_ctx_modnofound.py
- nooz/165.feature.rst
- requirements-test.txt
- setup.py
- tests/conftest.py
- tests/test_context_stream_semantics.py
- tests/test_debugger.py
- tests/test_docs_examples.py
- tests/test_spawning.py
- tractor/_actor.py
- tractor/_debug.py
- tractor/_portal.py
- tractor/_root.py
- tractor/_spawn.py
Some fixes for handling `SIGINT` / control-c when running in ~guest~ debug mode and dealing with `pdb` internals that [swap out the `sigint` handler from under our feet](https://github.com/python/cpython/blob/master/Lib/pdb.py#L344).
~This resolves an issue when running the `Qt` loop in guest mode where control-c *after* a `tractor.breakpoint()` was resulting in a hang. There were 2 problems:~
~- our [handler](https://github.com/goodboy/tractor/blob/master/tractor/_debug.py#L135) was borked (bad type signature)~
~- if we receive `SIGINT` in the root process we should always tear down the actor tree~
There's been a long-standing bug to do with the root actor getting stuck hanging for the tty lock to release after a child locks it then becomes uncontactable over IPC.
Part of that was due …
> Ignore SIGINT when in a debugger REPL

- .github/workflows/ci.yml
- docs/README.rst
Factoring out the history from #322 since we have other PRs which also need this to run clean 😂.
Also makes it easier to reference this specific change.
---
We are **disabling windows from CI** since there are clearly a few [unexpected (and frankly unexplainable) regressions](https://github.com/goodboy/tractor/actions/runs/3000118896/jobs/4814595104) which seem to be mostly due to windows runs getting **even slower** yet again (see streaming test fixtures) and we have no collaborator actively hacking on the *great tina OS*. 
So until we get someone who cares, we're disabling it all.
We are of course leaving in the existing support but there's no guarantees about functionality or correctness until someone comes who can verify it and help fix it 😂 (hint @chrizzFTD)..
In other words it's …
> Disable win tests in CI

- nooz/324.bugfix.rst
- tractor/_debug.py
- tractor/trionics/_mngrs.py
Tidbit case I missed in #165 where the completion event may have already been set back to `None` and we can get an attr error..
> Add debug complete event `None`-guard for when already reset

- tests/test_runtime.py
- tests/test_spawning.py
- tractor/_runtime.py
expose the runtime-lifetime exit stack as a `Actor.lifetime_stack` and add a small test suite that ensures it cleans up local filesystem files on crashes and cancels in a child actor.
Note: this is an undocumented API used in `piker` and is likely to be updated/change.
> Expose lifetime stack as class attr, add base test suite

- setup.py
As per the ongoing work in #333 we are currently broken on latest `trio` due to the new `ExceptionGroup` changes / support in the stdlib and we need to avoid using `0.22` until that work is complete.
> Pin pre-0.22 bc exception groups break everything

- nooz/336.trivial.rst
- tractor/_portal.py
- tractor/trionics/__init__.py
- tractor/trionics/_mngrs.py
Replacement for #329 since we can't easily do the whole "one nursery per context def" style..
Adds a `key: Callable[..., Hashable]` support and moves `maybe_open_nursery()` into this `trionics._mngrs.py` module which allows for more dynamic control over hashing logic.
> Callable key maybe open context

- examples/debugging/multi_daemon_subactors.py
- examples/debugging/multi_nested_subactors_error_up_through_nurseries.py
- nooz/333.feature.rst
- setup.py
- tests/test_cancellation.py
- tests/test_debugger.py
- tests/test_infected_asyncio.py
- tests/test_local.py
- tests/test_runtime.py
- tractor/__init__.py
- tractor/_debug.py
- tractor/_exceptions.py
- tractor/_portal.py
- tractor/_root.py
- tractor/_runtime.py
- tractor/_spawn.py
- tractor/_state.py
- tractor/_supervise.py
- tractor/log.py
Attempting to get the new `py3.11` driven [exception group](https://peps.python.org/pep-0654/#exceptiongroup-and-baseexceptiongroup) backport support in. See [pep 654](https://peps.python.org/pep-0654/#handling-exception-groups) for dirty deats.
Pertains to fixing #332 and appears to have caused a bunch of test hangs particularly in the debugger suite (which I've manually verified) which need some investigation.
**UPDATE** tests now fixed with the landing of #337 🏄🏼
> `ExceptiongGroup`s and `trio>=0.22`

- nooz/344.bugfix.rst
- tests/test_clustering.py
- tests/test_debugger.py
- tractor/_clustering.py
- tractor/_discovery.py
- tractor/_entry.py
- tractor/_ipc.py
- tractor/_portal.py
- tractor/_runtime.py
- tractor/_supervise.py
- tractor/experimental/_pubsub.py
- tractor/log.py
- tractor/trionics/_mngrs.py
In response to a weird issue discovered by @guilledk where if you pass in a `mngrs=(<generator comprehension>)`, you end up with an empty sequence in the loop inside `trionics.gather_contexts()` and then  a hang due to waiting on the `all_entered: trio.Event` [just after the loop](https://github.com/goodboy/tractor/blob/master/tractor/trionics/_mngrs.py#L123).
This solves the issue by greedly converting the `mngrs` sequence to a list and ensuring its size and otherwise raising a `ValueError`.
---
Further TODO for this to land:
- exact test failure [here in CI run](https://github.com/goodboy/tractor/actions/runs/3671732526/jobs/6207227497#step:6:18) from commit [c606be8](https://github.com/goodboy/tractor/pull/344/commits/c606be8c640d43da260ac1d457a3551150b3d85e)
- ~add tests for both the …
> Harden cluster tests

- nooz/349.trivial.rst
- setup.py
- tests/test_debugger.py
- tractor/_debug.py
- tractor/_runtime.py
- tractor/_spawn.py
Fixes a long running issue todo with ctl-c during `pdbpp` REPL use to ensure that the prompt is always redrawn after log msgs indicating that the SIGINT is being ignored in whatever actor currently owns the TTY lock / is running a REPL.
Also, this resolves the issues (AFAIK) that were preventing us from using the `pypi` version of `pdbpp` as mentioned in https://github.com/goodboy/tractor/issues/323. So we should be able to do a working release again 😂 ?
Probably pertains to:
- #148 (of which most questions i think are answered at this point?)
- https://github.com/goodboy/tractor/issues/113 which is our wish list of features.
> Re-draw `pdbpp` prompt on `SIGINT`

- tests/conftest.py
- tractor/_root.py
This is the start to adjusting the public API to support a so called *registry* system for actor discovery as per https://github.com/goodboy/tractor/issues/216.
For now we're just adding a deprecation warning which should serve drive the actual internal renaming and implementation desired by both #216 and #296.
> Begin deprecation of `arbiter_addr` -> `registry_addr`

- nooz/343.trivial.rst
- tests/test_advanced_streaming.py
- tests/test_task_broadcasting.py
- tractor/__init__.py
- tractor/_portal.py
- tractor/_streaming.py
- tractor/trionics/_broadcast.py
Originally driven by a bug found in `piker` where we'd get an inf recursion error due to `BroadcastReceiver.receive()` being recursively called when consumer tasks are awoken but no value is ready to `nowait` receive.
- This new rework takes an approach closer to the interface and internals of `trio.MemoryReceiveChannel` particularly in terms of,
- implementing a `BroadcastReceiver.receive_nowait()` and using it within the async `.receive()`
- failing over to an internal `._receive_from_underlying()` when the `_nowait()` call raises `trio.WouldBlock`
- adding `BroadcastState.statistics()` for debugging and testing
- dropping recursion from `.receive()`
- adds an internal `BroadcastReceiver._raise_on_lag: bool` which can be set to avoid `Lagged` errors from being raised in the case where a …
> Avoid inf recursion in `BroadcastReceiver.receive()`

- nooz/356.trivial.rst
- tractor/_spawn.py
It's been deprecated since `0.20.0` and we need to implement hard kill
semantics ourselves now instead of relying on the prior
`trio.Process.aclose()` wrapping; see #330!
---
for getting the functionality out of the old `Process.aclose()` if we
still need it in our spawning layer.~~
- see #330 for the details on all that and history behind the api
changes in `trio`.
for now what was an attempt to fix the `mypy` run..
`do_hard_kill()` with comments on the original source.
> What to do about `trio.Process.aclose()`?

- docs/README.rst
- examples/debugging/restore_builtin_breakpoint.py
- nooz/358.feature.rst
- requirements-test.txt
- setup.py
- tests/test_debugger.py
- tractor/__init__.py
- tractor/_debug.py
- tractor/_root.py
- tractor/_supervise.py
A ton of thanks to @mdmintz for the fork and fix of `pdbpp` in the new
and improved `pdbp`: https://github.com/mdmintz/pdbp
It would seem pretty much all the outstanding issues we had with `pdbpp`
are non-existent in the new project 💃🏼 , so i think other then running
this in my production dev eng for a bit, we can probably just land this
pronto 😎 
---
crashes (when using `--pdbp` flag; seems completely resolved now
i've been wanting works just fine in vim mode?
which solves the whole resized-terminal-messes-with-vertical-line-spacing.
> Switch to `pdbp` 🏄🏼 

- docs/README.rst
- examples/debugging/asyncio_bp.py
- setup.py
- tests/test_context_stream_semantics.py
- tests/test_debugger.py
- tests/test_legacy_one_way_streaming.py
- tractor/__init__.py
- tractor/_context.py
- tractor/_debug.py
- tractor/_root.py
- tractor/_rpc.py
- tractor/_runtime.py
- tractor/_spawn.py
- tractor/_supervise.py
- tractor/devx/__init__.py
- tractor/devx/_debug.py
- tractor/devx/_stackscope.py
- tractor/devx/cli.py
- tractor/to_asyncio.py
As a place to start organizing all our *developer experience* tools
and subsystems including,
- `._debug`: our multi-process-safe debugger REPL using `pdbp`
- `.pretty_struct`: holds some minor extensions to `msgspec.Struct`
for prettier console `repr()`.
- `._stackscope`: draft support for using the lovely
[`stackscope`](https://github.com/oremanj/stackscope) to render
task per-actor stack-trees on `SIGUSR1` for tracing hanging
`trio`/`tractor` apps.
- `.cli`: for now an optional idea for a `typer`/`click` plugin-hook
thing to enable capturing `--pdb` and `--ll` flags via a `ctx:
typer.Context.runtime_vars: dict`; something pulled out of a client
repo-project.
---
- very very early draft support for using
[`greenback`](https://github.com/oremanj/greenback) to implement …
> Start ` tractor.devx` sub-pkg

- pytest.ini
- tests/conftest.py
- tests/test_cancellation.py
- tests/test_child_manages_service_nursery.py
- tests/test_debugger.py
- tests/test_discovery.py
- tests/test_infected_asyncio.py
- tests/test_inter_peer_cancellation.py
- tests/test_legacy_one_way_streaming.py
- tests/test_local.py
- tests/test_multi_program.py
- tests/test_pubsub.py
- tests/test_rpc.py
- tests/test_spawning.py
- tests/test_task_broadcasting.py
- tractor/__init__.py
- tractor/_discovery.py
- tractor/_entry.py
- tractor/_ipc.py
- tractor/_multiaddr.py
- tractor/_portal.py
- tractor/_root.py
- tractor/_runtime.py
- tractor/_spawn.py
- tractor/_state.py
- tractor/_supervise.py
Mostly like it sounds. Adds support for actors to bind transport
layer sockets on multiple network addresses in anticipation of
supporting both multiple (transport layer or higher) protocols in
tandem as well as nested protocol tunneling with `wireguard` and
`ssh`.
Still missing is a [`libp2p` style multiaddress](https://github.com/libp2p/specs/blob/master/addressing/README.md#addressing-in-libp2p--)
parser which I will patch in from another repo shortly. Longer run
the idea is to use multiaddrs to drive both per-actor transport
*socket binds / listens* **and** outbound connection requests for
remote peers across da internetz.
---
That is on another non-AI mined git-service ;P
> Multihomed transport (server) addrs 🕶️ 

- examples/debugging/multi_daemon_subactors.py
- tests/test_advanced_faults.py
- tests/test_cancellation.py
- tests/test_child_manages_service_nursery.py
- tests/test_context_stream_semantics.py
- tests/test_debugger.py
- tests/test_docs_examples.py
- tests/test_infected_asyncio.py
- tests/test_inter_peer_cancellation.py
- tests/test_rpc.py
- tests/test_spawning.py
- tractor/_exceptions.py
- tractor/_rpc.py
From the [introducing commit's msg](https://github.com/goodboy/tractor/pull/373/commits/c1e0328669f70cec92bb2ea784c184b9b4c45e33),
> Since adding more complex inter-peer (actor) testing scenarios, we
definitely have an immediate need for `trio`'s style of "inceptions" but
for nesting `RemoteActorError`s as they're relayed through multiple
actor-IPC hops. So for example, a remote error relayed "through" some
proxy actor to another ends up packing a `RemoteActorError` into another
one such that there are 2 layers of RAEs with the first
containing/boxing an original src actor error (type).
See that commit's very in depth explanation for more deats ;)
----
Also includes matching updates to the tests (which should mostly be
running green now :fingers_crossed:) and in particular extension of …
> Remote inceptions: improved `RemoteActorError` boxing of inter-actor exceptions

- examples/debugging/asyncio_bp.py
- examples/debugging/multi_daemon_subactors.py
- examples/debugging/multi_nested_subactors_error_up_through_nurseries.py
- examples/debugging/multi_subactors.py
- examples/debugging/per_actor_debug.py
- examples/debugging/root_actor_breakpoint_forever.py
- examples/debugging/subactor_breakpoint.py
- examples/debugging/subactor_error.py
- examples/debugging/sync_bp.py
- tests/test_debugger.py
- tests/test_infected_asyncio.py
- tractor/_child.py
- tractor/_context.py
- tractor/_entry.py
- tractor/_root.py
- tractor/_rpc.py
- tractor/_runtime.py
- tractor/_spawn.py
- tractor/_state.py
- tractor/_supervise.py
- tractor/devx/_code.py
- tractor/devx/_debug.py
- tractor/devx/_stackscope.py
- tractor/log.py
- tractor/to_asyncio.py
Refinements to `tractor.pause_from_sync()` using the always lovely
`greenback` 😎
Alongside just getting everything working better from `trio.Task`s
that want to pause from sync functions,
- now supports use from any `trio.Task` **and** any sync thread
started with `trio.to_thread.run_sync()`.
- paired new test in suite `test_pause_from_sync` wrapping
a `examples/debugging/sync_bp.py`.
- support by default with with the `breakpoint()` builtin by
setting `os.environ.get('PYTHONBREAKPOINT')` in `._root`.
- guarding against `breakpoint()` usage (by raising a `RuntimeError`
if a new `maybe_enable_greenback: bool` and `debug_mode` are
**not** set.
- extend the `._state._runtime_vars: dict` with a `use_greenback:
bool` field.
- initial provisions for usage from infected-`asyncio`-mode even …
> Pause from sync (with `greenback`), `log.devx()`, hide `@acm` frames

- tests/test_shm.py
- tractor/_shm.py
Initial module import from `piker.data._sharemem` and first implementation of the system(s) discussed in #339.
---
- ~~[ ] force push from gitea branch to trigger CI runs~~
- yeah actions CI is being too finicky and there's a buncha
downstream branches built on this already so, we don't really
care and everyone is manually testing locally anyway Bp
- ~~[ ] merge on gitea and close this PR manually.~~
- nah we'll just merge here since it's been sitting here forever..
> Shared memory array API and optional tight integration with `numpy`

- docs/README.rst
- examples/advanced_faults/ipc_failure_during_stream.py
- examples/debugging/root_cancelled_but_child_is_in_tty_lock.py
- examples/debugging/shield_hang_in_sub.py
- tests/conftest.py
- tests/ipc/__init__.py
- tests/ipc/test_multi_tpt.py
- tests/ipc/test_server.py
- tests/test_advanced_faults.py
- tests/test_discovery.py
- tests/test_resource_cache.py
- tests/test_trioisms.py
- tractor/_testing/addr.py
- tractor/_testing/pytest.py
- tractor/ipc/_server.py
Follow up to  #375 adding,
- multi-IPC transport parametrization controls to the test harness
via a new `--tpt-proto` arg
- a first draft micro-suite of unit-tests for the new
`tractor.ipc._server` subsys APIs
- pluginize-ation of various useful (and general) fixtures and CLI
flags for consumption in dependent projects which are built on
`tractor` as a runtime, previously these only were found in
specific `conftest.py` files but now can be included via,
```python
pytest_plugins: tuple[str] = (
"tractor._testing.pytest",
)
```
- any other make CI green.
---
Follow-through from #375
----
- a couple test suite(s) of tests to audit `.ipc._server`
---
Still Todo before landing
------
root and subactors.
- cherried-as, 31df976 Add an `enable_transports` test-suite
- cherried-as, cc1de6c Drop …
> Multi ipc testing

- tractor/_entry.py
- tractor/devx/pformat.py
- tractor/log.py
- tractor/msg/pretty_struct.py
See explanation in #381 about both this *sclang* markup-idea as well
as longer term intentions to pretty-fy a bunch of our primitives
`.__repr__()` using it.
Note, that this patch is just providing the format rendering
machinery via,
- a new `.devx.pformat` mod offering a slew of new helpers,
-  specifically a `.devx.pformat.nest_from_op()` which is the prime
formatter util-fn for composing *sclang ops symbols* around
logging-emits pertaining to various runtime-primitive *status
reporting* (more will be explained obvious in a the follow up
patch which actually uses this stuff ;)
Also included but **not** pertaining specifically to this *sclang markup* stuff,
- a refactor to `.msg.pretty_struct` moving the core
`Struct.pformat()` method to a mod-fn for terser usage without
having to care …
> A "sclang" pformat-ing, `.msg.pretty_struct.pformat` and `modden.repr` utils bonanza

- tests/test_context_stream_semantics.py
- tests/test_remote_exc_relay.py
- tests/test_trioisms.py
- tractor/_exceptions.py
- tractor/_root.py
- tractor/_rpc.py
- tractor/_supervise.py
- tractor/devx/debug/_post_mortem.py
- tractor/to_asyncio.py
- tractor/trionics/__init__.py
- tractor/trionics/_beg.py
- tractor/trionics/_mngrs.py
- tractor/trionics/_taskc.py
As critiqued heavily (by me) over the past few months (after
discovering this *issue* during work on another dependent project) in
the `trio` chat room, i was able to hack together a near term soln
which at least resolves the bulk of critical potential issues (the
SC-cross-process semantics breaking kind) within the `tractor`
runtime - namely ensuring error propagation is maintained with
a (remote) child-task started with `Portal.open_context()` .
---
It's actually been documented and discussed for much longer then
I had thought and is most simply detailed in [this comment](https://github.com/python-trio/trio/issues/455#issuecomment-498603702)
which contains the following snippet.
```python
async def main():
with trio.CancelScope() as scope:
try:
raise RuntimeError("Oooops")
finally: …
```
> Coping with "`finally` footguns": avoiding `trio.Cancelled` exc masking as best we can..

- tests/ipc/test_each_tpt.py
- tractor/_context.py
- tractor/_portal.py
- tractor/_rpc.py
- tractor/ipc/_chan.py
- tractor/ipc/_mp_bs.py
- tractor/ipc/_shm.py
- tractor/ipc/_transport.py
- tractor/ipc/_uds.py
Various improvements to `.ipc` primitives interfaces including,
- `Channel.closed/.cancel_called`
- for UDS (`.ipc._uds`),
- 123999b4 assign `.l/raddr` in `.connect_to()` such that we always (*can*) assign the peer
end's PID on the `._raddr`.
- 3ece5213 implicitly create the `Address.bindspace: Path`
- dc6e9ec0eb Multi-line-style up the UDS fast-connect handler
---
- 561be209 Handle "out-of-layer" remote `Context` cancellation
- 09128c2 Log "out-of-layer" cancellation in `._rpc._invoke()`
- dc6e9ec, df0426b3: (reverted) Translate CRE's due to socket-close to tpt-closed
---
- 5021514
> Introspect-ipc: some `.ipc` subpkg iface refinements for reading cancel statuses and `Address.__repr__()`

- tractor/_runtime.py
- tractor/_supervise.py
Pretty succinct,
- enforce named-args to `tractor.open_nursery()`
- mk `ActorNursery` look like `trio.CancelScope` for cancel status fields by adding,
- `.cancel_called`
- `.cancelled_caught`
- deprecate `.[_]cancelled`
- Drop (the oddly) unused `Actor._root_n`
> A bit of (actor) nursery cleaning

- tests/test_infected_asyncio.py
- tractor/to_asyncio.py
Shocker, another `piker.brokerd.ib` discovered bug after updating to
py3.13 (and new `trio`).
Turns out any exc being raised prior to the first `.started()`-like
`to_trio.send_nowait()` call were not being propagated to the top of
the call stack (only `log.exception()` output if you scrolled up the
console hist..) making it confusing to grok where
a `.open_channel_from()` task crashed.
Instead this ensures that if the `to_trio: trio.abc.SendChannel`
closes (gracefully), thus raising a `trio.EndOfChannel` on the
`trio`-side, we check for an aio-side exc and ensure it's propagated
via `translate_aio_errors()`.
---
- 4a7491b test-driven-dev suite to catch the *exc raised pre-`chan.send_nowait()`* case
which should fail without a matching fix
- bd14830 actual fix for ^ by ensuring errors …
> `to_asyncio` eoc signal: use `trio.EndOfChannel` to indicate (maybe non-graceful) `asyncio.Task` termination
